Nueva idea de negocio
ignaciotitos/IV---HealthForAll pull request #4
Opened 2022-09-19 11:09 UTC by ignaciotitos

2022-09-20 10:59 UTC, JJ commented
Sin lista de comprobación es muy posible que haya algún error.

2022-09-20 11:00 UTC, JJ requested changes
Lee los comentarios.

2022-09-20 11:00 UTC, JJ commented on README.md
> +
Lo que hay en este PR son dos líneas en blanco. No puedo revisar a menos que el texto que sea parte de este objetivo aparezca en las diferencias. Te dije que lo hicieras desde el principio. Si no lo has hecho, simplemente haz algún cambio en las líneas originales de forma que aparezcan como cambiadas.

2022-09-20 15:45 UTC, ignaciotitos commented
@JJ mire usted a ver si ya está solucionado.

2022-09-20 17:49 UTC, JJ commented
Sigues sin haber repasado la lista de comprobación.

2022-09-20 17:50 UTC, JJ commented
¿Has pulsado en "Files changed"? ¿Qué es lo que te sale?

2022-09-21 06:53 UTC, ignaciotitos commented
En files changed no me aparece nada.

2022-09-21 06:53 UTC, ignaciotitos commented
These merge commits were added into this branch cleanly.
There are no new changes to show.

Me aparece esto exactamente.

2022-09-21 06:54 UTC, ignaciotitos commented
No se donde está o que es la lista de comprobación que menciona, he visto en otros repositorios de compañeros una lista con varios puntos sobre la lógica del negocio, si soluciona problemas planteados, etc pero no se donde está, en el guión del objetivo 0 no lo he visto.

2022-09-21 06:56 UTC, ignaciotitos commented
Vale, acabo de encontrar la lista de comprobación.

2022-09-21 07:33 UTC, ignaciotitos commented
Ya debería de salir.

2022-09-21 07:36 UTC, JJ requested changes
Aparte de lo comentado, tampoco tienes ningún tipo de justificación de por qué sería una aplicación en la nube.

2022-09-21 07:36 UTC, JJ commented on README.md
> +Es sabido como el auge de la comodidad para que te traigan la comida a casa se ha normalizado en nuestro tiempo. También es sabido como la mayoría de ventas son de pizzerías o comidas rápidas para te
¿Cuál es el problema que quieres resolver y para quién?

2022-09-21 07:36 UTC, JJ commented on README.md
> +Por eso que propongo tener al alcance en una misma aplicación todos los productos para potenciar el mercado local para pequeños negocios, en el que los clientes puedan comprar a través de la aplicaci
¿Qué lógica de negocio tiene?

2022-09-21 07:42 UTC, ignaciotitos commented on README.md
> +Es sabido como el auge de la comodidad para que te traigan la comida a casa se ha normalizado en nuestro tiempo. También es sabido como la mayoría de ventas son de pizzerías o comidas rápidas para te
El problema a resolver es que la gente deja muy de lado los comercios locales que venden productos que se pueden adquirir en supermercados. Esto es para potenciar estos pequeños negocios y poner en mano de todo el mundo ese tipo de productos, sobre todo está dirigido a la gente joven para que puedan estar al tanto de la existencia de estos y cojan productos de mejor calidad, y para las personas que ya van para que se los puedan llevar a casa, ver como están los productos del día...

2022-09-21 07:59 UTC, ignaciotitos commented on README.md
> +Por eso que propongo tener al alcance en una misma aplicación todos los productos para potenciar el mercado local para pequeños negocios, en el que los clientes puedan comprar a través de la aplicaci
Tener todos los datos de las fruterías, pescaderías, carnicerías con sus productos y con su precio además de mostrar los negocios que estén cerca del cliente.

2022-09-21 08:03 UTC, JJ commented on README.md
> +Por eso que propongo tener al alcance en una misma aplicación todos los productos para potenciar el mercado local para pequeños negocios, en el que los clientes puedan comprar a través de la aplicaci
"Tener datos" no es una lógica de negocio. Por favor, consulta el apartado correspondiente en el guión.

2022-09-21 08:04 UTC, JJ commented on README.md
> +Es sabido como el auge de la comodidad para que te traigan la comida a casa se ha normalizado en nuestro tiempo. También es sabido como la mayoría de ventas son de pizzerías o comidas rápidas para te
Por favor, consulta en el guién qué tipo de problemas son aceptables para la asignatura y como llevar a cabo el proceso de design thinking para concretarlos.

2022-09-21 09:57 UTC, ignaciotitos commented on README.md
> +Por eso que propongo tener al alcance en una misma aplicación todos los productos para potenciar el mercado local para pequeños negocios, en el que los clientes puedan comprar a través de la aplicaci
Realmente es recoger los datos de los negocios, y al tener los datos y el cliente puedo hacerle recomendaciones de sitios cercanos, con mejores precios, que estén dirigidos para el cliente. ¿Eso no se puede?

2022-09-21 10:14 UTC, ignaciotitos commented on README.md
> +Es sabido como el auge de la comodidad para que te traigan la comida a casa se ha normalizado en nuestro tiempo. También es sabido como la mayoría de ventas son de pizzerías o comidas rápidas para te
¿Me puede decir porque no es posible realizar esta propuesta?

En referente a la nube, sería una aplicación en la que no puede estar centralizada, porque para lo que está pensada sería para nivel nacional, para todo el mundo, por lo que necesita de estar alojada en la nube.

En cualquier caso por favor dígame por que no se puede, entiendo que es necesario parte de computación para la aplicación, pero al final se desplegará y es necesario programarla.

Las preguntas desde mi más sincera humildad, sólo quiero entender.

2022-09-21 10:36 UTC, JJ commented on README.md
> +Por eso que propongo tener al alcance en una misma aplicación todos los productos para potenciar el mercado local para pequeños negocios, en el que los clientes puedan comprar a través de la aplicaci
Insisto, ¿cuál es la lógica de negocio y de qué forma resuelve qué problema?

2022-09-21 10:38 UTC, JJ commented on README.md
> +Es sabido como el auge de la comodidad para que te traigan la comida a casa se ha normalizado en nuestro tiempo. También es sabido como la mayoría de ventas son de pizzerías o comidas rápidas para te
> El problema a resolver es que la gente deja muy de lado los comercios locales que venden productos que se pueden adquirir en supermercados. Esto es para potenciar estos pequeños negocios y poner en mano de todo el mundo ese tipo de productos, sobre todo está dirigido a la gente joven para que puedan estar al tanto de la existencia de estos y cojan productos de mejor calidad, y para las personas que ya van para que se los puedan llevar a casa, ver como están los productos del día...

Ese no es el problema. Es la consecuencia del problema. Y si fuera un problema, lo sería de los comercios, no de los usuarios. Los usuarios no van a usar una aplicación para resolver el problema de otra gente. Cada persona quiere resolver su problema.

2022-09-21 10:59 UTC, ignaciotitos commented on README.md
> +Es sabido como el auge de la comodidad para que te traigan la comida a casa se ha normalizado en nuestro tiempo. También es sabido como la mayoría de ventas son de pizzerías o comidas rápidas para te
Claro, el problema es de los comercios. Y para resolver ese problema va dirigido a los clientes, que son el objetivo final.

2022-09-21 11:03 UTC, JJ commented on README.md
> +Es sabido como el auge de la comodidad para que te traigan la comida a casa se ha normalizado en nuestro tiempo. También es sabido como la mayoría de ventas son de pizzerías o comidas rápidas para te
En ingeniería del software se resuelve problema de *un cliente* mediante un programa informático para *ese cliente*. Si requieres resolver el problema de *otro* cliente para ello, tienes que formular también ese problema claramente. En este caso, los usuarios (gente) no tienen ningún problema. Compran en el supermercado o tiendecilla que les apetece.
Por favor, lee también el primer elemento de la lista de comprobación, que es tener conocimiento personal del problema (y el cliente). Comprar en supermercados (o tiendecillas) no es tener conocimiento perosnal del problema.

2022-09-21 11:04 UTC, JJ commented on README.md
> +Por eso que propongo tener al alcance en una misma aplicación todos los productos para potenciar el mercado local para pequeños negocios, en el que los clientes puedan comprar a través de la aplicaci
> Lógica del negocio: Procesar y almacenar los datos de los comercios, en el que ellos mismos puedan insertar sus productos con sus respectivos precios.
> 

Por favor, léete el guión en el apartado que dice qué lógicas de negocio son y no válidas.

> Resolver problema: Los usuarios finales pueden tener en la aplicación los pequeños comercios cercanos a sus viviendas y así poder comprar en esos lugares y no en supermercados.

¿Los usuarios tienen el problema de que no saben qué comercios son cercanos a sus viviendas? Ese es el problema que estás resolviendo.

2022-09-21 16:55 UTC, ignaciotitos commented on README.md
> +Por eso que propongo tener al alcance en una misma aplicación todos los productos para potenciar el mercado local para pequeños negocios, en el que los clientes puedan comprar a través de la aplicaci
No, estoy resolviendo la comodidad del comprador de no comprar a la ligera en un supermercado productos que pueden ser mejores en comercios pequeños e igual de cerca que el supermercado pero que ni siquiera piensa en acercarse ya que en el supermercado tiene todos los productos y no tiene que dar varias vueltas.

2022-09-21 16:55 UTC, ignaciotitos commented on README.md
> +Por eso que propongo tener al alcance en una misma aplicación todos los productos para potenciar el mercado local para pequeños negocios, en el que los clientes puedan comprar a través de la aplicaci
Pero bueno, voy a cambiar de idea.

2022-09-21 17:57 UTC, JJ approved these changes
Es cierto que tendría que estar en la nube, porque quienes ofertan y buscan plazas tendrían que acceder a una instancia común. El resto, me tempo que todavía tiene que repasarse un poco.
La idea parece factible, pero tendrías que definir el problema un poco más  en la fase de enfatizar. ¿Dónde se recoge? ¿Cuanto se cobra? ¿Se hace cada día o por semanas o meses?
En todo caso, tienes que prever qué lógica de negocio vas a usar, y que se pueda hacer dentro de los límites de la asignatura.

2022-09-21 17:57 UTC, JJ commented on README.md
> +Para le gente que vive a las afueras de la ciudad es un grán problema el hecho de tener que ir a la facultad o el centro para estudiar / trabajar. Sobre todo enfocado a los estudiantes. Ya que estos
En general, los problemas del mundo físico no son los que se pueden resolver por programas, y menos en esta asignatura. Pero vamos a suponer que es un contexto, y seguir adelante.

2022-09-21 17:57 UTC, JJ commented on README.md
> +Crear una aplicación que conecte al cliente (usuarios que utilicen transporte público) con las personas que dispongan de coche y también vayan a la facultad o alrededores en el mismo período de tiemp
Las fases del design thinking sirven para algo. No puedes saltarte dos o tres fases y pasar directamente de "empatizar" (qué problema ir en transporte público al trabajo) a proponer algo sin ni siquiera definir cuál es el problema (y qué se puede resolver)
Incluso aunque esto resolviera el problema, no parece que esto tenga más lógica de negocio que buscar coches que te lleven a un lado. Por favor, consulta las lógicas de negocio aceptables.

2022-09-21 17:57 UTC, JJ commented on README.md
> +Esto implica filtrar por horas en las que el cliente necesite el transporte y por la zona en la que resida o en la que esté en el momento que lo necesite.
Sigue siendo una simple búsqueda.

2022-09-21 17:57 UTC, JJ commented on README.md
> +Esta se basa en la optimización del tiempo del estudiantado y no tardar tanto tiempo en ir a la facultad desde la casa o viceversa, o tener que hacer a los padres ir a recogerlos ya que estos estarán
La lógica de negocio son los cálculos o procesamiento sobre la información que tienes para producir el resultado que resuelva el problema. Por favor, revisa la presentación sobre lógica de negoio para entender el concepto, y cuales son las aceptables para la asignatura.

2022-09-21 17:58 UTC, JJ requested changes
Perdón, dado a aprobar sin querer. Tienes que hacer algunas modificaciones.

2022-09-22 09:12 UTC, ignaciotitos commented on README.md
> +Para le gente que vive a las afueras de la ciudad es un grán problema el hecho de tener que ir a la facultad o el centro para estudiar / trabajar. Sobre todo enfocado a los estudiantes. Ya que estos
Las recogidas se establecerían dentro de la aplicación y se dejarían libres para contactar entre el cliente y el ofertante. Entre ellos pueden hablar para ver donde quedar, o sino en todo caso el ofertante es el que dice desde donde sale y a donde va. La parte del dinero la pondría el ofertante a cuánto dinero quiere cobrar el transporte. Según la distancia puede ser más o menos. Yo en mi cabeza tengo la idea de que sería cada día, ya que la gente necesita todos los días transporte para movilizarse de un lado para otro.

2022-09-22 09:36 UTC, ignaciotitos commented on README.md
> +Esta se basa en la optimización del tiempo del estudiantado y no tardar tanto tiempo en ir a la facultad desde la casa o viceversa, o tener que hacer a los padres ir a recogerlos ya que estos estarán
Muy bien, una lógica de negocio puede ser que a partir de los datos calcule diferentes rutas viables que puede tener el que oferta el coche con la API de google maps y que le aparezca a la gente para ver si es posible ir en ese coche o escoger otro con otra ruta

2022-09-22 09:45 UTC, JJ commented on README.md
> +Esta se basa en la optimización del tiempo del estudiantado y no tardar tanto tiempo en ir a la facultad desde la casa o viceversa, o tener que hacer a los padres ir a recogerlos ya que estos estarán
La lógica de negocio no puede confiar en ninguna API externa. Por favor, mira las preguntas frecuentes.

2022-09-22 09:53 UTC, ignaciotitos commented on README.md
> +Esta se basa en la optimización del tiempo del estudiantado y no tardar tanto tiempo en ir a la facultad desde la casa o viceversa, o tener que hacer a los padres ir a recogerlos ya que estos estarán
Lo de la API lo decía porque es más fácil con datos ya elaborados.

2022-09-22 10:07 UTC, JJ commented on README.md
> +Esta se basa en la optimización del tiempo del estudiantado y no tardar tanto tiempo en ir a la facultad desde la casa o viceversa, o tener que hacer a los padres ir a recogerlos ya que estos estarán
Os dije que trabajarais con cosas de las que tuvierais conocimiento entre otras cosas por eso, por los datos. Si no tienes los datos, no puedes solucionar el problema.

2022-09-22 16:46 UTC, ignaciotitos commented on README.md
> +Esto implica filtrar por horas en las que el cliente necesite el transporte y por la zona en la que resida o en la que esté en el momento que lo necesite.
No, ya que estas comparando las zonas en la que está el que ofrece el coche con el que lo busca, comparando los horarios para el trayecto y si se dirigen al mismo destino. Estas haciendo una búesqueda muy selectiva.

2022-09-22 16:47 UTC, ignaciotitos commented on README.md
> +Esto implica filtrar por horas en las que el cliente necesite el transporte y por la zona en la que resida o en la que esté en el momento que lo necesite.
Además de que al crear la oferta para el pasaje dices desde dónde sales, el que está buscando podría saber cuanto tiempo hay entre su localización y la zona de salida, por lo que habría que calcularlo con coordenadas.

2022-09-22 17:55 UTC, JJ commented on README.md
> +Esto implica filtrar por horas en las que el cliente necesite el transporte y por la zona en la que resida o en la que esté en el momento que lo necesite.
> No, ya que estas comparando las zonas en la que está el que ofrece el coche con el que lo busca, comparando los horarios para el trayecto y si se dirigen al mismo destino. Estas haciendo una búesqueda muy selectiva.

Que sigue siendo búsqueda, no un algoritmo ni un procesamiento no trivial de la información. Si has almacenado cosas que estés buscando, te las devuelve. Si no, no. No hay lógica de negocio

2022-09-22 17:56 UTC, JJ commented on README.md
> +Esto implica filtrar por horas en las que el cliente necesite el transporte y por la zona en la que resida o en la que esté en el momento que lo necesite.
> Además de que al crear la oferta para el pasaje dices desde dónde sales, el que está buscando podría saber cuanto tiempo hay entre su localización y la zona de salida, por lo que habría que calcularlo con coordenadas.

"Además" no es algo que tengas que poner cuando describes *un* problema. O es parte del problema o no lo es. "Además" indica que no tienes claro qué problema estás resolviendo.

2022-09-23 10:02 UTC, ignaciotitos commented on README.md
> +Esta se basa en la optimización del tiempo del estudiantado y no tardar tanto tiempo en ir a la facultad desde la casa o viceversa, o tener que hacer a los padres ir a recogerlos ya que estos estarán
¿Podemos tener una tutoría? Ya sea presencial u online, no tengo problema. Usted me dice.

2022-09-24 08:29 UTC, JJ requested changes
Por favor, aclara el problema que realmente quieres solucionar y propón soluciones de las que tengas datos.

2022-09-24 08:29 UTC, JJ commented on README.md
> +Para le gente que vive a las afueras de la ciudad es un grán problema el hecho de tener que ir a la facultad o el centro para estudiar / trabajar. Sobre todo enfocado a los estudiantes. Ya que estos
Cuando se hace algún comentario, el sistema automáticamente lo descarta si haces cambios en la rama desde la que se hace el pull request. Si queréis resolver el comentario, esa es la forma de hacerlo, no mediante otros comentarios.

2022-09-24 08:29 UTC, JJ commented on README.md
> +Esta se basa en la optimización del tiempo del estudiantado y no tardar tanto tiempo en ir a la facultad desde la casa o viceversa, o tener que hacer a los padres ir a recogerlos ya que estos estarán
El jueves en la clase que corresponda a tu grupo, por ejemplo.

2022-09-24 08:29 UTC, JJ commented on README.md
> +Esta se basa en la optimización del tiempo del estudiantado y no tardar tanto tiempo en ir a la facultad desde la casa o viceversa, o tener que hacer a los padres ir a recogerlos ya que estos estarán
En todo caso, ¿qué es lo que no entiendes sobre que no se puede solucionar un problema del que no tienes datos?

2022-09-24 08:29 UTC, JJ commented on README.md
> +# Recomendador de Vuelos #IDEA 2
No podéis proponer nada más que un proyecto que vayáis a desarrollar. Yo no puedo elegir por vosotros.
Y, una vez más, tenéis que tener conocimiento personal y datos.

2022-09-30 10:33 UTC, ignaciotitos commented
Listo para revisar.

2022-09-30 12:05 UTC, JJ approved these changes
Como lo hablamos en clase, tienes que tener claro que la lógica de negocio en el objetivo 4 tienes que programarla tú, ¿no?

2022-10-06 17:27 UTC, merged